name: .NET

on:
  push:
    branches:
      - "**"

jobs:
  TikTovenaar:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build TikTovenaar/TikTovenaar.csproj
    - name: Test
      run: dotnet test
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TikTovenaar
        path: TikTovenaar\bin\Debug\net8.0-windows
  TikTovenaarAPI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build TikTovenaar.Api/TikTovenaar.Api.csproj
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TikTovenaarAPI
        path: TikTovenaar.Api\bin\Debug\net8.0
