name: .NET

on:
  push:
    branches:
      - "**"

jobs:
  TikTovenaar:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: API
      run: dotnet build TikTovenaar.Api\TikTovenaar.Api.csproj --runtime linux-x64 --configuration Release
    - name: Build installer
      run: dotnet build TikTovenaar.Installer\TikTovenaar.Installer.csproj --configuration Release
    - name: Run Installer Project
      run: dotnet run --project TikTovenaar.Installer/TikTovenaar.Installer.csproj --configuration Release
    - name: Upload TikTovenaar
      uses: actions/upload-artifact@v4
      with:
        name: TikTovenaar
        path: TikTovenaar\bin\Release\net8.0-windows
    - name: Upload TikTovenaarAPI
      uses: actions/upload-artifact@v4
      with:
        name: TikTovenaarAPI
        path: TikTovenaar.Api\bin\Release\net8.0\linux-x64
    -  name: Upload TikTovenaarInstaller
       uses: actions/upload-artifact@v4
       with: 
         name: TikTovenaarInstaller
         path: TikTovenaar.Installer\TikTovenaar.msi
    - name: Test
      run: dotnet test
           
